# Railway Nixpacks Configuration for Telesana
# This tells Railway how to build and run your Next.js app

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate deploy",
  "npm run build"
]

[start]
cmd = "npm start"
